# Generated by Django 2.1.5 on 2022-03-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
