# Generated by Django 2.1.5 on 2022-03-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0002_genre_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='totalSeasons',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
