# Generated by Django 2.1.5 on 2022-03-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0003_auto_20220301_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
