# Generated by Django 2.1.5 on 2022-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0004_auto_20220301_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
